### ISSUE TITLE
Can you add a demo?

### ISSUE THREAD

**Issue by DannyFeliz** [marverix/v-tostini#1]
Is easy create a demo using something like [Codesandbox](https://codesandbox.io/s/vue) also an image or something due when we're searching for some package that is UI related package the first thing we want to see is a little example of how it looks.

**Comment by marverix** [comment]
Hello, sorry that I didn't responded for so long. I have some issues with Github notifications - I didn't get any notification about this issue.
Sure, I will add something.
Br,
Marek

**Comment by marverix** [comment]
Is this sufficient? https://codesandbox.io/embed/vtostini-demo-btc4g

**Comment by DannyFeliz** [comment]
> Is this sufficient? [codesandbox.io/embed/vtostini-demo-btc4g](https://codesandbox.io/embed/vtostini-demo-btc4g)

Yes, that's enough 👍
