### ISSUE TITLE
[Feature request] src folder should be shipped together with dist folder so users of the lib could compile the code themselves

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [marverix/v-tostini#11]
v-tostini can be used in the environments that have their own compilation targets. 
User case: I use v-tostini with nuxt.js - that means that I can build it from the source by specifying 
```
build: {
    transpile: ['v-tostini']
}
```
that way a library will compile with the transpilation rules of my project, rather than v-tostini environment. That way I as an end-user can decide which browsers v-tostini should support.

**Comment by marverix** [comment]
Wow! How cool is that! I never dug deeper into the nuxt.js. Sure, I will release 1.2.1 in a second.

**Comment by AndrewBogdanovTSS** [comment]
With source available Nuxt can also include it in the modern build, so users of cutting edge browsers can benefit from untranspiled code while others can use compiled legacy bundle. https://nuxtjs.org/api/configuration-modern/

**Comment by marverix** [comment]
Done! Please update to `1.2.1` ! Hope it will work for you :)

**Comment by marverix** [comment]
@AndrewBogdanovTSS can you confirm?

**Comment by AndrewBogdanovTSS** [comment]
Hi @marverix , sorry I got carried away by some other stuff. Yes, now I can see `src` folder in the source and can successfully build from it. One thing needs to be changed in the code though, in order for it to work. Import should be made from `v-tostini/src` instead of `v-tostini` so it will look like this:

```
import Vue from 'vue'
import tostini from 'v-tostini/src'

Vue.use(tostini)
```

I suggest to update documentation with this example since it can be beneficial for Nuxt users. I can provide an info of how to setup this module in Nuxt - so you can just paste it in the docs.
