### ISSUE TITLE
[Feature request] Add support for custom templates

### ISSUE THREAD

**Issue by enkot** [marverix/v-tostini#13]
It would be great to have possibility to specify custom templates using scoped slots and make Tostini fully renderless. Usage:
```vue
<tostini-plate class="tostini-plate" v-slot="{ type, message }">
  <div class="tostini" :data-type="type">
    {{ message }}
  </div>
</tostini-plate>
```

**Comment by marverix** [comment]
Cool! I like it!

**Comment by enkot** [comment]
@marverix Also added "close" handler to scoped slot :) Please, check it.

**Comment by marverix** [comment]
Added and released in v1.3.0. Big big thanks to you and your friend! I have updated README, and added Contributors section (before License).

**Comment by enkot** [comment]
> Added and released in v1.3.0. Big big thanks to you and your friend! I have updated README, and added Contributors section (before License).

Big thanks to you for library and fast feedback!

**Comment by marverix** [comment]
Released v1.3.1. Please confirm that it's working. 🍻

**Comment by enkot** [comment]
Works great. 👌🍻

**Comment by marverix** [comment]
Closing then
