### ISSUE TITLE
[Feature request] Add support for transitions

### ISSUE THREAD

**Issue by enkot** [marverix/v-tostini#14]
It would be great to have possibility to use v-tostini with transitions by specifying transition name. Usage example:
```vue
<tostini-plate transition-name="fade" />
```

**Comment by marverix** [comment]
I merged you PR, but I needed to do it locally because of conflicts. Could you check out if it works?

**Comment by marverix** [comment]
Added and released in v1.3.0.

**Comment by marverix** [comment]
Released v1.3.1. Please confirm that it's working. 🍻

**Comment by marverix** [comment]
Closing then
