### ISSUE TITLE
Add a way global duration and/or a way to add duration to the calculation

### ISSUE THREAD

**Issue by imagoiq** [marverix/v-tostini#20]
Hi,

It seems that there are no way to add a global duration, am I right ? It would be nice, now that we can add transition, to add either our custom duration for all instances or to add the transition duration to the calculation.

What do you think ?

**Comment by marverix** [comment]
Hi @imagoiq ,
I'm sorry for so long response time. I have nothing against your idea. Could you create a pull request?
