### ISSUE TITLE
[Feature request] Add support for html based strings

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [marverix/v-tostini#5]
I really like the idea of this library and it's minimalistic look. One thing that I do miss though is the ability to pass html based string into tostini e.g. to show a link to a user in the text.

**Comment by marverix** [comment]
Sure. It's easy to do - I will add such possibility (after #6  will be resolved). But we warned that it will be on dev side to sanitize this HTML string :)

**Comment by marverix** [comment]
Hey, please update version to `1.1.0` and here is how to:
https://github.com/marverix/v-tostini#html-support
