### ISSUE TITLE
[Bug] Unable to use the lib with default Vue runtimeCompiler

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [marverix/v-tostini#6]
Looking into the code you are using template option that is not available with default Vue runtime compiler setting https://cli.vuejs.org/config/#runtimecompiler
Please, rewrite the template to use render function

**Comment by marverix** [comment]
Hey, thanks for reporting! And thanks to @enkot for taking care of it.

**Comment by AndrewBogdanovTSS** [comment]
@marverix we are on the same team, so we decided to cooperate on making this lib better 😁

**Comment by marverix** [comment]
Great to hear that! I have recently full hands of works, so I'm really happy that you like this lib and decided to contribute! :)

**Comment by marverix** [comment]
Released with 1.1.0 - please confirm that it works and if so then close issue :)

**Comment by enkot** [comment]
@marverix @AndrewBogdanovTSS Checked it, works fine :)

**Comment by marverix** [comment]
Closing then. Thanks one more time guys for help!
