### ISSUE TITLE
Totstini is not working in IE11 - support should be added

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [marverix/v-tostini#8]
There are 2 ways IE11 can be supported:
1. Use ES5 syntax while developing
2. Creating 2 builds: modern/legacy
Which way do you think will be better @marverix ?

I also suggest exposing `src` folder (for some reason I don't see it in node_modules when the module is installed ) - so it can be processed by the external build system.

**Comment by AndrewBogdanovTSS** [comment]
Sorry, this is a proper pull request https://github.com/marverix/v-tostini/pull/10

**Comment by marverix** [comment]
As commented in #10 - I didn't saw that. When I saw #9, I already started to add Babel into Rollup :)

**Comment by marverix** [comment]
Please pull version 1.2.0

**Comment by AndrewBogdanovTSS** [comment]
@marverix could you also expose `src` folder in the npm module, right now I only see `dist` https://take.ms/9q7pn
Regarding 1.2.0 - it's working fine in IE11 now, thanks!

**Comment by marverix** [comment]
@AndrewBogdanovTSS could you write to what you need `src` exposed on npm module? I just want to understand use case. You can write new issue for that if you want to.

**Comment by AndrewBogdanovTSS** [comment]
@marverix https://github.com/marverix/v-tostini/issues/11
